"""
CodeLoom GitHub Integration Module.
Provides secure token vaulting, async GitHub REST API transport, OAuth connection management,
and verified patch publication to GitHub repositories.
"""

from .models import (
    TokenType,
    GitHubCredential,
    GitHubUser,
    GitHubRepository,
    GitHubBranch,
    GitHubCommit,
    GitHubRateLimitInfo,
    PublicationResult,
    PublicationStatus,
)
from .exceptions import (
    GitHubError,
    GitHubAPIError,
    GitHubAuthenticationError,
    GitHubAuthorizationError,
    GitHubNotFoundError,
    GitHubConflictError,
    GitHubValidationError,
    GitHubRateLimitError,
    GitHubTimeoutError,
    GitHubNetworkError,
    CredentialVaultError,
    EncryptionKeyMissingError,
    DecryptionError,
    CredentialExpiredError,
    GitHubAuthError,
    GitHubAuthNotConfiguredError,
    GitHubAuthorizationDeniedError,
    GitHubInvalidStateError,
    GitHubStateExpiredError,
    GitHubTokenExchangeError,
    GitHubIdentityLookupError,
    GitHubOpenRedirectError,
    PublicationError,
    RemediationNotFoundError,
    RemediationNotVerifiedError,
    InvalidPatchFingerprintError,
    BaseCommitStaleError,
    PatchApplicationError,
    GitHubBranchCreationError,
    GitHubCommitCreationError,
    GitHubPullRequestCreationError,
)
from .vault import TokenVault
from .client import GitHubClient
from .config import GitHubConfig
from .auth import GitHubAuthManager
from .publisher import (
    GitHubPublisher,
    canonicalize_diff,
    compute_patch_fingerprint,
    apply_unified_diff,
    store_authoritative_remediation,
    get_authoritative_remediation,
)

__all__ = [
    "TokenType",
    "GitHubCredential",
    "GitHubUser",
    "GitHubRepository",
    "GitHubBranch",
    "GitHubCommit",
    "GitHubRateLimitInfo",
    "PublicationResult",
    "PublicationStatus",
    "GitHubError",
    "GitHubAPIError",
    "GitHubAuthenticationError",
    "GitHubAuthorizationError",
    "GitHubNotFoundError",
    "GitHubConflictError",
    "GitHubValidationError",
    "GitHubRateLimitError",
    "GitHubTimeoutError",
    "GitHubNetworkError",
    "CredentialVaultError",
    "EncryptionKeyMissingError",
    "DecryptionError",
    "CredentialExpiredError",
    "GitHubAuthError",
    "GitHubAuthNotConfiguredError",
    "GitHubAuthorizationDeniedError",
    "GitHubInvalidStateError",
    "GitHubStateExpiredError",
    "GitHubTokenExchangeError",
    "GitHubIdentityLookupError",
    "GitHubOpenRedirectError",
    "PublicationError",
    "RemediationNotFoundError",
    "RemediationNotVerifiedError",
    "InvalidPatchFingerprintError",
    "BaseCommitStaleError",
    "PatchApplicationError",
    "GitHubBranchCreationError",
    "GitHubCommitCreationError",
    "GitHubPullRequestCreationError",
    "TokenVault",
    "GitHubClient",
    "GitHubConfig",
    "GitHubAuthManager",
    "GitHubPublisher",
    "canonicalize_diff",
    "compute_patch_fingerprint",
    "apply_unified_diff",
    "store_authoritative_remediation",
    "get_authoritative_remediation",
]
