"""
Fix recommendation data model generated by template or AI reasoning.
"""
from datetime import datetime, timezone
from typing import Optional, List
from pydantic import BaseModel, Field


class Fix(BaseModel):
    fix_id: str
    cluster_id: str
    title: str
    explanation: str
    root_cause: str
    suggested_before: str
    suggested_after: str
    confidence: float
    tier: str  # template | light_ai | full_ai | dry_run
    tokens_used: int = 0
    requires_manual_review: bool = True
    validation_steps: List[str] = Field(default_factory=list)
    wcag_link: Optional[str] = None
    prompt_version: Optional[str] = None
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    specialist: str = "accessibility"  # accessibility | seo | performance
